AWSTemplateFormatVersion: "2010-09-09"
Description: Deploys CustomAction in SecurityHub to enable sending findings to Slack via AWS Chatbot
 
#==================================================
# Parameters
#==================================================
Parameters:
  SlackWorkSpaceID:
    Description: Slack workspace ID (Copy and Paste from AWS Chatbot Configured Clients Interface)
    Type: String
    MinLength: 9
    MaxLength: 15
    AllowedPattern: ^[a-zA-Z0-9_]*$
    ConstraintDescription: |
      Malformed Input Parameter: Environment must contain only upper and numbers. Length should be minimum of 9 characters and a maximum of 15 characters.
 
  SlackChannelID:
    Description: Slack Channel ID
    Type: String
    MinLength: 9
    MaxLength: 15
    AllowedPattern: ^[a-zA-Z0-9_]*$
    ConstraintDescription: |
      Malformed Input Parameter: Environment must contain only upper and numbers. Length should be a minimum of 9 characters and a maximum of 15 characters.

#==================================================
# Resources
#==================================================
Resources: 
  ChatBotManageIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "sns.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
  SlackChannelConfig:
    Type: AWS::Chatbot::SlackChannelConfiguration
    Properties: 
      ConfigurationName: securityhubnotification
      IamRoleArn: !GetAtt ChatBotManageIAMRole.Arn
      LoggingLevel: NONE
      SlackChannelId: !Ref SlackChannelID
      SlackWorkspaceId: !Ref SlackWorkSpaceID
        #      SnsTopicArns: 
        #        - !Ref  SNSTopicAWSChatBot
